module.exports = {
  apps: [
    {
      name: 'neuroedge-kernel',
      cwd: './kernel',
      script: 'bash',
      args: ['-lc', 'set -a; [[ -f .env ]] && source .env; set +a; exec go run ./cmd/api'],
      autorestart: true,
      restart_delay: 3000,
      max_restarts: 100,
      exp_backoff_restart_delay: 200,
      min_uptime: '10s',
      max_memory_restart: '1G',
      time: true,
      out_file: '/tmp/neuroedge-core/kernel.pm2.out.log',
      error_file: '/tmp/neuroedge-core/kernel.pm2.err.log',
      merge_logs: true,
    },
    {
      name: 'neuroedge-ml',
      cwd: './ml',
      script: 'bash',
      args: ['-lc', '[[ -f .venv/bin/activate ]] && source .venv/bin/activate; set -a; [[ -f .env ]] && source .env; set +a; exec python server.py'],
      autorestart: true,
      restart_delay: 3000,
      max_restarts: 100,
      exp_backoff_restart_delay: 200,
      min_uptime: '15s',
      max_memory_restart: '2G',
      time: true,
      out_file: '/tmp/neuroedge-core/ml.pm2.out.log',
      error_file: '/tmp/neuroedge-core/ml.pm2.err.log',
      merge_logs: true,
    },
    {
      name: 'neuroedge-orchestrator',
      cwd: './orchestrator',
      script: 'bash',
      args: ['-lc', 'set -a; [[ -f .env ]] && source .env; set +a; exec pnpm run dev'],
      autorestart: true,
      restart_delay: 3000,
      max_restarts: 100,
      exp_backoff_restart_delay: 200,
      min_uptime: '15s',
      max_memory_restart: '2G',
      time: true,
      out_file: '/tmp/neuroedge-core/orchestrator.pm2.out.log',
      error_file: '/tmp/neuroedge-core/orchestrator.pm2.err.log',
      merge_logs: true,
      wait_ready: false,
    },
  ],
};
