import os
from typing import Dict, List
from .storage import OUTPUTS_DIR, ensure_dirs, new_id


def generate_subtitles(text: str) -> Dict[str, object]:
    ensure_dirs()
    lines: List[str] = [ln.strip() for ln in (text or "").splitlines() if ln.strip()]
    if not lines:
        lines = ["Generated by NeuroEdge VisionForge"]
    out_id = new_id("sub")
    srt_path = os.path.join(OUTPUTS_DIR, f"{out_id}.srt")
    current = 0
    with open(srt_path, "w", encoding="utf-8") as f:
        for idx, ln in enumerate(lines, start=1):
            t0 = f"00:00:{current:02d},000"
            t1 = f"00:00:{current+2:02d},000"
            f.write(f"{idx}\n{t0} --> {t1}\n{ln}\n\n")
            current += 2
    return {"srt_path": srt_path, "segments": len(lines)}

